'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Key2Rs232vb.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _0800808001355198716_tmpred_bl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0800808001355198716.tmpred_bl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _0800808001355198716_tmpred_bl__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0800808001355198716.tmpred_bl (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blank_keyboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank keyboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blank_keyboard1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank keyboard1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property red_bl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_bl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property retrocraft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("retrocraft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property retrocraft2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("retrocraft2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
