%  Yordan Lasonov - September 2012
% 
%  This MATLAB script will export filter coefficients to a header file
%
%  Just change the first line to match the m-file that was generated by
%  the FDA tool.  The header file name and also the coefficient array
%  name can be modified.

filt = treble_filt();  % change this name bird_filter to your filter name
fd=fopen('treble_filt.h','wt');
fprintf(fd,'#define FILTER_SIZE %d \nfloat filt[%d]={%.9g',length(filt.Numerator),length(filt.Numerator),filt.Numerator(1));
fprintf(fd,',\n %.9g',filt.Numerator(2:end));
fprintf(fd,'};\n');
fclose(fd)